hed-standard/hed-javascript

- package.json
- tests/schema.spec.js
- utils/xpath.js
- validators/schema.js
This branch rewrites the schema parsing code to use the pure-JS xml2js library, along with a temporary kludge to parse two types of XPath queries while I'm waiting on the author of xml2js-xpath to fix several bugs that prevent me from using it here.
> xml2js rewrite

- tests/data/HED7.1.1.xml
- tests/hed.spec.js
- tests/schema.spec.js
- utils/__tests__/hed.spec.js
- utils/__tests__/string.spec.js
- utils/string.js
- validators/hed.js
This implements the `clockTime` unit class. The code will now check if `clockTime` is a valid unit class and validates as a clock time if it exists and is a unit class of the tag in question. Then, if `clockTime` is not in the schema, it does the same thing with the `time` unit class. If `time` is not a valid unit class, no clock time validation is performed.
The test cases have been updated to v7.1.1 of the schema and all pass with the new code.
> Implement clockTime unit class

- tests/hed.spec.js
- tests/schema.spec.js
- utils/__tests__/hed.spec.js
- utils/hed.js
- utils/issues.js
- validator/hed.js
- validator/schema.js
This branch splits string-level validation from event-level validation. The new string-level validation skips tag group-level and top-level checks, including required and unique tag checks. It also handles `#` placeholders for values as an option, in order to support BIDS and other possible uses.
Extensions now are warned in all cases, and value tags are no longer included in the overall tag list.
Fixes #8
> Split event- and string-level validation

- tests/event.spec.js
- utils/issues.js
- validator/event.js
The previous version treated placeholders for child tags as valid. This PR fixes that issue.
> Treat all placeholders for non-takesValue tags as invalid

- converter/__tests__/converter.js
- tests/dataset.spec.js
- tests/event.spec.js
- validator/event.js
- validator/stringParser.js
This PR removes support for tilde validation, as brought up in https://github.com/hed-standard/hed-specification/issues/171. A couple of other lingering issues have also been fixed, including one regarding the passing of tag conversion issues through the string parser back to the main validation code.
> Remove tilde support

- converter/__tests__/converter.js
- converter/converter.js
- converter/issues.js
- tests/dataset.spec.js
- tests/event.spec.js
- tests/stringParser.spec.js
- utils/index.js
- utils/issues.js
- validator/dataset.js
- validator/event.js
- validator/stringParser.js
This commit merges the two issue generating modules into `utils/issues.js`, creates a new Issue type for issues, and changes the export list for `utils/issues.js` to also export the new type. The `converter/issues.js` module was kept as a wrapper to deal with conversion-specific functionality. The `noValidTagFound` error code was deleted as redundant and merged into `invalidTag`. All other issue codes were left unmodified pending the finalization of the HED 3 error code specification. All instances of issue generation in validation and test code were updated, and all tests pass. The Issue object is backwards-compatible, as the fields have the same names as before, so no major version bump is needed.
> Revamp issue handling

- converter/__tests__/converter.js
- converter/converter.js
- converter/schema.js
- tests/event.spec.js
- tests/stringParser.spec.js
- utils/schema.js
- validator/event.js
- validator/schema.js
- validator/stringParser.js
This PR passes HED 2 strings through a modified short-to-long conversion as part of the string parsing process. It also adds a new syntax-only placeholder validation check (`#` counts only), and string-level syntax checks now always run even if string parsing has errors. The tests have been adjusted and should pass, and other minor fixes have been made.
Fixes #18
> Use Mapping for HED 2 strings and various other fixes

- .github/workflows/ci.yml
- converter/__tests__/converter.js
- converter/converter.js
- converter/schema.js
- tests/dataset.spec.js
- tests/event.spec.js
- tests/schema.spec.js
- tests/stringParser.spec.js
- utils/__tests__/hed.spec.js
- utils/__tests__/string.spec.js
- utils/hed.js
- utils/issues.js
- utils/schema.js
- utils/string.js
- validator/dataset.js
- validator/event.js
- validator/schema.js
- validator/stringParser.js
This pull request adds a bevy of changes to the codebase:
- String parsing refactored, with new types added and all tags now being passed through short-to-long conversion before performing semantic validation.
- Tilde validation removed, and tildes are now treated as invalid.
- New placeholder and definition syntax validation checks added.
- Unit and value validation rewritten.
- Several changes to tests.
- Remote library schema loading support added.
> Myriad of HED 3-related changes

- tests/event.spec.js
- utils/hed.js
- utils/issues.js
- validator/event.js
- validator/stringParser.js
This branch implements support for the `tagGroup`, `topLevelTagGroup`, and `unitPrefix` schema attributes.
> Implement tag group and prefix unit attribute support

- tests/event.spec.js
- tests/stringParser.spec.js
- utils/issues.js
- validator/event.js
- validator/stringParser.js
I've created a new type, `ParsedHedGroup`, to encapsulate tag group data. This allows us to iterate over the tags and nested inner tag groups more cleanly. The duplicate tag validation was completely rewritten, and it now displays errors for both duplicate tags. The issue with tag bounds within groups has been fixed, and all tags are now pegged to the full string. Additional tests have been added to ensure proper behavior.
> Rewrite tag group parsing

- tests/event.spec.js
- utils/__tests__/hed.spec.js
- utils/hed.js
- utils/issues.js
- validator/event.js
This PR rescopes the `allowPlaceholders` argument to `validateHedString` to more explicitly handle BIDS sidecar value strings. It now creates an issue if a standalone (i.e. non-definition) value placeholder (i.e. a `#` character) is missing when this parameter is `true`.
> Rescope placeholder parameter

- converter/issues.js
- tests/dataset.spec.js
- tests/event.spec.js
- tests/stringParser.spec.js
- utils/index.js
- utils/issueData.js
- utils/issues.js
- utils/issues/data.js
- utils/issues/issues.js
- utils/string.js
- validator/event.js
This PR streamlines the issue implementation by moving the data to a new module and using a template literal parser copied from MDN to simplify the interpolation stage. Both modules have been moved to a new folder.
> Streamline issues

- converter/types.js
- tests/stringParser.spec.js
- utils/issues/issues.js
- utils/schema.js
- validator/schema.js
- validator/stringParser.js
This PR converts the ES5-style constructor functions to ES6-style classes. The BIDS and event tests work, so the syntax checks out.
> Use ES6 classes instead of basic constructor functions

- tests/schema.spec.js
- validator/schema/types.js
This PR rewrites the HED 3 schema parsing tests to use the new schema entry class structure introduced in #56. I've also added a default unit property to `SchemaUnitClass`, which was missed earlier.
> Port HED 3 schema parsing tests to new class structure

- tests/dataset.spec.js
This commit adds a duplicate of the existing mutiple-event test using the `validateHedDataset` function. It also tests the `duplicateDefinition` issue generation, which hopefully should confirm that the current code has the desired behavior.
> Add dataset-level tests with and without definitions

- bids/index.js
- bids/tsvParser.js
- bids/types.js
- bids/validate.js
- tests/bids.spec.js
- validator/dataset.js
- validator/event/init.js
This will implement support for validating HED data in non-event BIDS data. It includes a new type (`BidsTabularFile`) and a restructuring of `BidsTsvFile`. `validateHedDataset` and `validateHedDatasetWithContext` now accept a settings object as the last argument.
> Implement validation for non-event TSV files

- validator/schema/types.js
This PR fixes the plural unit bug in issue #129. It also generally refactors the `SchemaUnit` constructor and adds documentation.
Fixes #129
> Fix plural units in HED 3 code

- bids/types/json.js
- bids/types/tsv.js
- bids/validator/bidsHedTsvValidator.js
- common/issues/issues.js
- parser/parsedHedString.js
This PR creates new classes for TSV rows (wrapping `ParsedHedString`) and sidecar keys. Much of the sidecar key parsing code has been moved to the new class.
> Create new classes for TSV rows and sidecar keys

- parser/main.js
- parser/parsedHedTag.js
- parser/splitHedString.js
- tests/event.spec.js
- validator/event/hed3.js
This PR revamps the interim value validation regex from a whitelist of characters to a blacklist of special and illegal characters. Realizing these are general syntax rules throughout the string, the test was moved to the `ParsedHed3Tag` construction call chain.
Tabs are now substituted with spaces, similarly to the existing behavior with ASCII NUL characters.
> Refactor interim value validation

- parser/parsedHedTag.js
This PR adds complete optional chaining for schema references in `ParsedHedTag`. I also rewrote documentation in that module.
Fixes #128
> Fix unescaped schema references and documentation in ParsedHedTag

- bids/types/tsv.js
- bids/validator/bidsHedTsvValidator.js
- utils/map.js
This PR merges TSV rows with the same onset into a single `BidsTsvEvent` object (for timeline TSV files only) and sorts them by their onset value.
> Make TSV validation event-based

- package-lock.json
- package.json
- tests/bids.spec.js
- utils/files.js
This fixes #146. It also bumps the Node dependency to 18.0.0 to match bids-validator.
> Switch HTTP requests from then-request to Fetch API

- bids/schema.js
- common/issues/data.js
- common/schema/types.js
- converter/converter.js
- converter/schema.js
- converter/types.js
- tests/bids.spec.data.js
- tests/bids.spec.js
- tests/data/HED_testlib_2.1.0.xml
- tests/data/HED_testlib_3.0.0.xml
- tests/event.spec.js
- tests/schema.spec.js
- validator/schema/hed3.js
- validator/schema/init.js
- validator/schema/types.js
This PR implements support for merging partnered schemas with the same `withStandard` XML attribute into the same `Schema` object, thereby treating them as a single schema. It provides the required validation of schema compatibility, the code to actually merge the data, and tests.
> Implement support for merging lazy partnered schemas

- bids/schema.js
- bids/validate.js
- common/issues/data.js
- common/schema/config.js
- common/schema/loader.js
- common/schema/types.js
- converter/__tests__/converter.spec.js
- converter/index.js
- converter/schema.js
- tests/bids.spec.data.js
- tests/bids.spec.js
- tests/dataset.spec.js
- tests/event.spec.js
- tests/schema.spec.js
- tests/stringParser.spec.js
- utils/__tests__/hed.spec.js
- validator/index.js
- validator/schema/init.js
This PR removes the schema loading code that no longer matches the current HED standard. It also cleans up some tests and adds other minor improvements.
> Remove experimental schema loading code

- bids/types/issues.js
- bids/validate.js
This simple PR adds `dataset_description.json` as the file for certain internal errors when validating BIDS datasets.
> Add dataset_description.json as file for certain internal errors

- .github/workflows/publish.yml
This PR allows us to publish npm releases directly from GitHub when we create new GitHub releases.
> Publish npm releases from GitHub Actions

- bids/types/tsv.js
The constructor's type check for a plain object was catching typed objects as well. The new code explicitly checks for `Map`s, and plain objects are checked with the `isPlainObject` lodash function.
> Fix type-checking bug in BidsTsvFile constructor

- bids/types/issues.js
- common/issues/data.js
This will provide useful error messages for BIDS validation output.
> Use BidsHedIssue and Issue for internal error reporting

- fileTransformer.js
This fixes XML file transformation on Windows by converting the Windows-style line endings to Unix-style line endings. It also streamlines the replacements by using `JSON.stringify()`.
> Fix XML file transformation

- parser/main.js
- tests/event.spec.js
This is for compliance with the spec.
> Use commaMissing issue for missing comma before tag group

- .codespellrc
- .github/workflows/ci.yml
- .gitignore
- package.json
- spec_tests/javascript_tests.json
- spec_tests/jsonTests.spec.js
- tests/bids.spec.js
- validator/event/validator.js
- validator/specialTags.json
This includes the initial version of the testing based on JSON unit tests.
> Initial commit of the spec testing

- parser/parsedHedGroup.js
- tests/event.spec.js
- validator/event/validator.js
This PR fixes the duplicate tag check. There were two issues. First, the subgroup array iterator in `ParsedTagGroup` was only returning the tags, excluding any groups. Also, only the top-level tags (not groups) were checked. Both were fixed, and the ensuing issue with the unique tag check was also mitigated. The JSON spec tests for duplicate tags were ported to the main JavaScript testcases for verification.
In order to make the sidecar tests pass, tag level validation (duplicate and unique tags) were moved up to string-level validation.
> Fix duplicate tag check

- bids/types/json.js
- bids/types/tsv.js
- bids/validator/bidsHedSidecarValidator.js
- common/issues/data.js
- spec_tests/jsonTests.spec.js
- tests/bids.spec.js
This PR fixes several issues related to sidecar syntax. It also fixes a few issues with the JSON spec test runner.
> Fix sidecar syntax issues

- bids/validator/bidsHedTsvValidator.js
- parser/parsedHedGroup.js
- spec_tests/jsonTests.spec.js
This PR fixes a bug with tag group equivalence determination that was caused by the set difference function call only being made in one direction. This fixes the tests broken by the merging of #192 and #193. It also deletes a semicolon from the commented-out auxiliary spec file line.
> Fix bug with tag group equivalence that was causing tests to fail

- common/issues/issues.js
This parallels the method in `BidsIssue` of the same name.
The static method `Issue.issueListWithValidStatus` was also documented.
> Add isError method to Issue class

- bids/schema.js
- bids/types/json.js
- bids/types/tsv.js
- bids/validator/bidsHedSidecarValidator.js
- common/issues/issues.js
- common/schema/loader.js
- parser/converter.js
- parser/parsedHedGroup.js
- utils/types.js
- validator/schema/hed3.js
This merges the `throw`, the creation of the `IssueError`, and the generation of the `Issue` into a single call.
> Move all throws of IssueError to new static method

- parser/parsedHedTag.js
- parser/splitHedString.js
- tests/bids.spec.js
- tests/dataset.spec.js
- tests/stringParser.spec.js
- utils/hedData.js
- validator/hed2/parser/parsedHed2Tag.js
Also fix testcases to remove now-deleted duplicate messages and bad outputs.
> Throw errors from ParsedHedTag constructors instead of using field

- parser/converter.js
- parser/parsedHedGroup.js
- parser/parsedHedTag.js
- tests/event.spec.js
- validator/event/hed3.js
- validator/event/validator.js
- validator/hed2/event/hed2Validator.js
This PR moves testing for the `requireChild` schema attribute in HED 3 to `TagConverter`. It also simplifies the conversion code.
> Move HED 3 requireChild testing to TagConverter and refactor that class

- .github/workflows/ci.yml
We are switching to using a develop branch with master being the stable branch for releases.
> Added develop branch to github ci action

- schema/entries.js
- schema/parser.js
- schema/schemaMerger.js
This will avoid directly setting private fields from outside code (poor coding practice) and ensure the fields are only set once.
> Create and use setters for private fields in SchemaTag

- package-lock.json
- package.json
This "sphinx" (https://www.npmjs.com/package/sphinx) is entirely unrelated to the Sphinx used by Read the Docs, and it is thus unnecessary,
> Remove "sphinx" dev dependency

- .github/dependabot.yml
Chai v5 does not work with the current code, so we skip it here.
> Ignore chai major version updates in Dependabot config

- .github/workflows/ci.yml
This will provide added detail for the CI.
> Add JSON spec tests as separate GitHub action

- spec_tests/javascriptTests.json
- spec_tests/jsonTests.spec.js
- src/bids/types/file.js
- src/issues/data.js
- src/issues/issues.js
Removed DEPRECATED_VERSION and STYLE__WARNING.  Replaced GENERIC_ERROR with INTERNAL_ERROR.
> Updated the error codes

- .husky/pre-commit
- package.json
husky is a development package whose configuration we borrowed from the old bids-validator package. It has since been updated, and the existing configuration was creating warnings. This PR updates the configuration. It also now runs both sets of tests when committing.
> Update husky configuration

- src/bids/datasetParser.js
- src/bids/types/__tests__/dataset.spec.js
- src/bids/types/dataset.js
- src/issues/data.js
- src/utils/files.js
This PR reorganizes the file-loading code and fixes most of the imports to conform to the rest of the code (which mostly uses ES Module syntax). The new test module could not be fully converted due to limitations in Jest.
One test currently fails. The code works, but I didn't bother fixing the test to match the new `IssueError`-based error return.
> Reorganize file loading and fix import syntax

- .codespellrc
These files may contain "misspelled" names, but we don't care about those.
> Exclude package.json and package-lock.json from codespell checks

- .github/workflows/publish.yml
This is necessary for upcoming releases.
> Restore NPM publish GitHub Action accidentally deleted earlier

- src/bids/schema.js
- src/schema/init.js
- src/schema/specs.js
- src/utils/string.js
- tests/jsonTests/schemaSpecTests.spec.js
- tests/otherTests/schema.spec.js
This truncates the BIDS schema support to a single function. The new function generating schemas from version strings has been moved to `schema/init.js` (below `buildSchemas`).
I would prefer to rename `buildSchemasFromVersion` to `buildSchemasFromVersionString` if possible. The skipped tests need to be fixed or deleted, as the function they test no longer exists.
> Move version spec parsing to Schema(s)Spec classes

- .github/workflows/publish.yml
This is required for OIDC support.
> Install current version of npm in publish script

- esbuild.mjs
- package.json
- scripts/test-types-local-unix.sh
- scripts/test-types-local.js
This makes the browser build the sole ESM build, hopefully restoring the sanity of the 4.0.x series.
> Merge ESM builds
