hed-standard/hed-javascript

tests/event.spec.js
utils/__tests__/hed.spec.js
utils/hed.js
utils/issues.js
validator/event.js

This PR rewrites value validation to bring it in line with the HED 3 spec. This necessitated a merge and refactoring of the unit validation functions as well. Tests were updated.
Fixes #14
Fixes #15

Rewrite value and unit validation

---

utils/issues.js

This branch will add HED 3 error codes to the issue data and report the issues using a standardized format. The levels have been split to a separate field to aid in this and to provide parsable detail. I'll also eventually include the fixes to tilde validation in this branch.

Reorganize issues

---

tests/event.spec.js
utils/__tests__/hed.spec.js
utils/hed.js
utils/issues.js
validator/event.js
validator/stringParser.js

This PR implements string-level placeholder validation. I'll fill this description in more later.

Placeholder validation

---

utils/xpath.js

This PR cleans up the XPath module quality. It's a first test for the new Code Climate integration.

Clean up XPath module

---

tests/bids.spec.js
validator/bids.js
validator/index.js

This PR moves most of the HED-specific BIDS validation code to this package.

Migrate BIDS code to hed-javascript

---

converter/schema.js
package-lock.json
package.json
utils/array.js
utils/schema.js

This PR will contain various Code Climate fixes.

Code Climate fixes

---

data/HED8.0.0.xml
tests/schema.spec.js
utils/schema.js

This PR implements support for loading a fallback schema XML file (bundled with the code) if loading the requested schema fails.
The file name and version number (the latter in the test case) are hardcoded in the code. We may want to look into a global configuration file for stuff like that which changes frequently. Perhaps they can be stored in `package.json`?

Implement support for loading a fallback schema

---

utils/issues/data.js
utils/schema.js
validator/bids/types.js
validator/bids/validate.js
validator/schema.js

This PR adds the bundled fallback schema and implements several new BIDS support classes. It also hides internal JavaScript errors behind Issue objects.

Implement fallback schemas and several changes to schema loading and BIDS code

---

utils/__tests__/array.spec.js
utils/__tests__/map.spec.js
utils/array.js

Also surround array tests with describe block and adjust type in `flattenDeep` JSDoc.

Add test for filterNonEqualDuplicates

---

validator/stringParser.js

This should improve the Code Climate score slightly.

Refactor similar string parsing issue merge code into new function

---

common/schema/loader.js
common/schema/types.js
validator/schema/init.js

Flatten schemas

---

tests/bids.spec.js

Library schemas added missing expected issues message

---

common/schema/types.js
tests/bids.spec.js
validator/bids/schema.js

Removed the remaining test conflicts due to the resolve -> reject change.

Fixed some of the tests in bids spec

---

.eslintrc.json
common/issues/issues.js
common/schema/types.js
converter/types.js
tests/schema.spec.js
utils/string.js
utils/xml2js.js
utils/xpath.js
validator/bids/schema.js
validator/bids/types.js
validator/event/hed3.js
validator/event/validator.js
validator/parser/parsedHedGroup.js
validator/parser/parsedHedString.js
validator/parser/parsedHedSubstring.js
validator/parser/parsedHedTag.js
validator/schema/hed3.js
validator/schema/types.js

This PR will include advanced and newer syntax features enabled with the inclusion of esbuild.

Add advanced features (part 1)

---

common/schema/types.js
converter/converter.js
converter/schema.js
converter/types.js
tests/event.spec.js
utils/hedData.js
validator/hed2/parser/parsedHed2Tag.js
validator/parser/parsedHedTag.js
validator/schema/hed3.js
validator/schema/init.js
validator/schema/parser.js
validator/schema/types.js

This PR will contain tag conversion improvements, including restricting tag conversion to HED 3 tags and (hopefully) rewriting the schema parser used by the converter to use the main schema parser's output.

Tag conversion improvements

---

README.md

Added code-climate and version badges to README

Update README.md to have code climate badges

---

package-lock.json
package.json

Also adjust version lock to use "^".

Update package-lock.json for TypeScript

---

readthedocs.yml

Requested by notification from readthedocs

Updated the readthedocs.yml

---

docs/requirements.txt
docs/source/conf.py
docs/source/index.rst
readthedocs.yml

@happy5214 please merge when you have a chance.

Updated readthedocs configuration as required

---

readthedocs.yml

Relocated jobs to build section

---

bids/schema.js
bids/types/issues.js
common/schema/loader.js
converter/converter.js
data/HED_testlib_2.0.0.xml
package-lock.json
package.json
tests/data/HED_testlib_2.0.0.xml
utils/array.js
utils/files.js
utils/string.js
validator/schema/types.js

This PR contains several changes from #147 that are not directly related to lazy partnered schemas, as well as a couple of other minor additions. They are being ported here in order to create a new patch release.

Various fixes ported from the lazy partnered schemas branch

---

converter/__tests__/converter.spec.js
tests/dataset.spec.js
tests/schema.spec.js
validator/schema/init.js

Right now, this removes the last call to `Promise.then` in the main code and trials `async` in the dataset tests. It could be expanded later

More async usage

---

utils/types.js

Also declare property map as explicit field.
Fixes #198

Convert Memoizer back to plain class

---

package-lock.json
package.json
src/bids/schema.js
src/issues/data.js
src/issues/issues.js
src/schema/parser.js
tests/testData/schemaBuildTests.data.js

This PR fixes three Code Climate issues.

Several Code Climate fixes

---

.codeclimate.yml

This PR streamlines up the exclude patterns and raises the complexity and identical/similar code thresholds to prevent nuisance issues.

Clean up Code Climate configuration

---

spec_tests/jsonTests.spec.js
src/bids/types/file.js
src/bids/types/json.js
tests/bidsTests.spec.js
tests/schemaBuildTests.spec.js
tests/schemaSpecTests.spec.js
tests/testData/bidsTests.data.js

This PR fixes the BIDS-format "file" objects used primarily for error reporting.

Fix BIDS-format "file" objects

---

src/bids/types/json.js
src/issues/data.js
src/issues/issues.js
tests/otherTests/bidsIssues.spec.js
tests/otherTests/issueParameters.spec.js

Added tests and improved error context in messages.

Worked through issues in BidsSidecar

---

.qlty/qlty.toml

The existing Qlty configuration simply did not work. I used the default config and added our paths. It can be adjusted as needed.

Re-create Qlty configuration from defaults

---

browser/src/utils/files.js
browser/vite.config.js

These are replaced in the vite configuration with the browser versions.

Replaced the files module in browser

---

package-lock.json
package.json

This reverts the split of ESM build configurations, hopefully fixing the remaining build issues.

Release version 4.1.4

---

browser/src/components/ErrorDisplay.jsx
src/parser/parsedHedTag.js
tests/jsonTestData/bidsTests.data.js
tests/jsonTestData/definitionManagerValidationTests.data.js
tests/jsonTestData/tagParserTests.data.js

Changed output download of errors to json
